---
- name: set metadata to an instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - instance_autofailover_vars.yml
    - clouds.yml
  environment:
    OS_AUTH_URL: "{{ clouds[target_cloud]['auth']['auth_url'] }}"
    OS_PROJECT_ID: "{{ clouds[target_cloud]['auth']['project_id'] }}"
    OS_DOMAIN_NAME: "{{ clouds[target_cloud]['auth']['domain_name'] }}"
    OS_USER_DOMAIN_NAME: "{{ clouds[target_cloud]['auth']['user_domain_name'] }}"
    OS_USERNAME: "{{ clouds[target_cloud]['auth']['username'] }}"
    OS_PASSWORD: "{{ clouds[target_cloud]['auth']['password'] }}"
    OS_IDENTITY_API_VERSION: "{{ clouds[target_cloud]['identity_api_version'] }}"
  tasks:
    - name: set metadata to an instance
      command: >-
        openstack
        server set
        --property fcx.autofailover={{ exec_autofailover }}
        {{ instance_id }}
      environment: "{{ proxy_env }}"

    - name: get instance infomation
      command: >-
        openstack
        server show
        -f yaml
        {{ instance_id }}
      register: show_instance
      changed_when: false
      environment: "{{ proxy_env }}"

    - name: check instance metadata
      assert:
        that: >-
          "\"fcx.autofailover='{{ exec_autofailover }}'\" in (show_instance.stdout | from_yaml)['properties']"
        msg: "metadata is not set."

